server:
  port: 9000
  
spring:
  application:
    name: zuul-gateway
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  retryable: true
  routes:
    order-service:
      path: /order/**