spring:
  application:
    name: eureka-demo

server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2:8760/eureka/
  server:
    enableSelfPreservation: false  # 自我保护，不下线服务实例